
export enum StatutCommande {
    PAYEE = "PAYEE",
    ANNULEE = "ANNULEE",
    EN_ATTENTE_VALIDATION = "EN_ATTENTE_VALIDATION",
    EN_ATTENTE_PAIEMENT = "EN_ATTENTE_PAIEMENT",
    REMBOURSEMENT_DEMANDE = "REMBOURSEMENT_DEMANDE",
    REMBOURSE = "REMBOURSE",
    LIVREE = "LIVREE"
}